# Generated by Django 2.1 on 2018-10-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('href', models.URLField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
            ],
        ),
    ]
