# Generated by Django 2.1 on 2018-10-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0002_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdfapp.Club'),
        ),
    ]
