# Generated by Django 2.1 on 2019-03-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdfapp', '0002_auto_20190306_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_years', models.IntegerField()),
                ('end_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('href', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('gallery_type', models.CharField(choices=[('PH', 'Foto'), ('VD', 'Vídeo')], default='PH', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('href', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(max_length=100)),
                ('href', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeoplePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rol_type', models.CharField(choices=[('ST', 'Técnico'), ('PL', 'Plantilla')], default='PL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('href', models.URLField()),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_calendar', models.URLField(blank=True, null=True)),
                ('url_results', models.URLField(blank=True, null=True)),
                ('url_classification', models.URLField(blank=True, null=True)),
                ('url_crossedtable', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='facebook_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='facebook_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='google_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='google_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
        migrations.RemoveField(
            model_name='club',
            name='instagram_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='instagram_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='sendmail_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='sendmail_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='twitter_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='twitter_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='youtube_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='youtube_text',
        ),
        migrations.AddField(
            model_name='club',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['host'], name='cdfapp_club_host_a97658_idx'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.People'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_alt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_alt', to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Rol'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Team'),
        ),
        migrations.AddField(
            model_name='teaminstallation',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Installation'),
        ),
        migrations.AddField(
            model_name='teaminstallation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Age'),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Season'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='peoplesocial',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.People'),
        ),
        migrations.AddField(
            model_name='peoplesocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Social'),
        ),
        migrations.AddField(
            model_name='peoplephoto',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.People'),
        ),
        migrations.AddField(
            model_name='peoplephoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='installationimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='installationimage',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdfapp.Installation'),
        ),
        migrations.AddField(
            model_name='installation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='installation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
        ),
        migrations.AddField(
            model_name='galleryobject',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='facility',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='cover',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='cover',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdfapp.News'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='clubsocial',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club'),
        ),
        migrations.AddField(
            model_name='clubsocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Social'),
        ),
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'number'], name='cdfapp_team_team_id_c5f9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['club', '-date_publication'], name='cdfapp_news_club_id_d274f4_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['club', 'gallery_type', '-date'], name='cdfapp_gall_club_id_4d6f29_idx'),
        ),
        migrations.AddIndex(
            model_name='cover',
            index=models.Index(fields=['club', 'active'], name='cdfapp_cove_club_id_0e6421_idx'),
        ),
    ]
