# Generated by Django 2.1 on 2019-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0003_auto_20190306_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='iframe',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
