# Generated by Django 2.1 on 2018-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
