# Generated by Django 2.1 on 2019-03-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0005_remove_sponsor_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEquipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
                ('image_back', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cdfapp.GalleryObject')),
                ('image_front', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cdfapp.GalleryObject')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Season')),
            ],
        ),
    ]
