# Generated by Django 2.1 on 2018-10-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0006_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['host'], name='cdfapp_club_host_a97658_idx'),
        ),
    ]
