# Generated by Django 2.1 on 2019-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0007_auto_20190308_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryobject',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
