# Generated by Django 2.1 on 2018-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0007_auto_20181018_1223'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['club', '-date_publication'], name='cdfapp_news_club_id_d274f4_idx'),
        ),
    ]
