# Generated by Django 2.1 on 2018-10-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0008_auto_20181022_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('gallery_type', models.CharField(choices=[('PH', 'Foto'), ('VD', 'Vídeo')], default='PH', max_length=2)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('href', models.URLField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Gallery')),
            ],
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['club', 'gallery_type', '-date'], name='cdfapp_gall_club_id_4d6f29_idx'),
        ),
    ]
