# Generated by Django 2.1 on 2019-03-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0008_auto_20190308_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationimage',
            name='title',
        ),
    ]
