# Generated by Django 2.1 on 2018-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0009_auto_20181022_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
