# Generated by Django 2.1 on 2018-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0011_auto_20181023_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
