# Generated by Django 2.1 on 2018-11-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0014_age_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.People')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.URLField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='peoplesocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Social'),
        ),
    ]
