# Generated by Django 2.1 on 2018-11-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0015_auto_20181116_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
            ],
        ),
        migrations.RemoveField(
            model_name='social',
            name='image',
        ),
        migrations.AlterField(
            model_name='peoplesocial',
            name='href',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='clubsocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Social'),
        ),
    ]
