# Generated by Django 2.1 on 2018-11-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0016_auto_20181119_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='facebook_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='facebook_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='google_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='google_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='instagram_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='instagram_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='sendmail_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='sendmail_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='twitter_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='twitter_text',
        ),
        migrations.RemoveField(
            model_name='club',
            name='youtube_href',
        ),
        migrations.RemoveField(
            model_name='club',
            name='youtube_text',
        ),
    ]
