# Generated by Django 2.1 on 2018-12-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0017_auto_20181120_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('href', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Age')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Season')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='preferential',
        ),
        migrations.AddField(
            model_name='cover',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cdfapp.News'),
        ),
        migrations.AddIndex(
            model_name='cover',
            index=models.Index(fields=['club', 'active'], name='cdfapp_cove_club_id_0e6421_idx'),
        ),
    ]
