# Generated by Django 2.1 on 2018-12-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0018_auto_20181211_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
