# Generated by Django 2.1 on 2018-12-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0019_auto_20181221_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rol_type', models.CharField(choices=[('ST', 'Técnico'), ('PL', 'Plantilla')], default='PL', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.People')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Rol')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Team')),
            ],
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'number'], name='cdfapp_team_team_id_c5f9e4_idx'),
        ),
    ]
