# Generated by Django 2.1 on 2019-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0021_auto_20190117_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url_crossedtable',
            field=models.URLField(blank=True, null=True),
        ),
    ]
