# Generated by Django 2.1 on 2019-01-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0022_team_url_crossedtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
            preserve_default=False,
        ),
    ]
