# Generated by Django 2.1 on 2019-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0023_teammember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='nick',
        ),
        migrations.AddField(
            model_name='teammember',
            name='nick',
            field=models.CharField(default='Nick', max_length=20),
            preserve_default=False,
        ),
    ]
