# Generated by Django 2.1 on 2019-01-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0024_auto_20190121_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject'),
            preserve_default=False,
        ),
    ]
