# Generated by Django 2.1 on 2019-02-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdfapp', '0025_team_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PeoplePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.People')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cdfapp.GalleryObject')),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_alt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='photo_alt', to='cdfapp.GalleryObject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='cdfapp.GalleryObject'),
        ),
    ]
